# Generated by Django 4.2.30 on 2026-05-28 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='last_alert_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
