# Generated by Django 4.2.30 on 2026-05-28 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_player_last_alert_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='last_alert_key',
        ),
    ]
