# Generated by Django 4.2.30 on 2026-05-30 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_player_last_alert_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='last_alert_key',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='last_ping',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
